import {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	NodeApiError,
	NodeOperationError,
	NodeConnectionTypes,
	JsonObject,
} from 'n8n-workflow';

const targetCountryOptions = [
	{ name: 'United States (US)', value: 'US' },
	{ name: 'France (FR)', value: 'FR' },
	{ name: 'United Kingdom (GB)', value: 'GB' },
	{ name: 'Canada (CA)', value: 'CA' },
	{ name: 'Germany (DE)', value: 'DE' },
	{ name: 'Italy (IT)', value: 'IT' },
	{ name: 'Spain (ES)', value: 'ES' },
	{ name: 'India (IN)', value: 'IN' },
	{ name: 'Brazil (BR)', value: 'BR' },
	{ name: 'Australia (AU)', value: 'AU' },

	{ name: 'AD', value: 'AD' },
	{ name: 'AE', value: 'AE' },
	{ name: 'AF', value: 'AF' },
	{ name: 'AG', value: 'AG' },
	{ name: 'AI', value: 'AI' },
	{ name: 'AL', value: 'AL' },
	{ name: 'AM', value: 'AM' },
	{ name: 'AO', value: 'AO' },
	{ name: 'AR', value: 'AR' },
	{ name: 'AS', value: 'AS' },
	{ name: 'AT', value: 'AT' },
	{ name: 'AW', value: 'AW' },
	{ name: 'AZ', value: 'AZ' },
	{ name: 'BA', value: 'BA' },
	{ name: 'BB', value: 'BB' },
	{ name: 'BD', value: 'BD' },
	{ name: 'BE', value: 'BE' },
	{ name: 'BF', value: 'BF' },
	{ name: 'BG', value: 'BG' },
	{ name: 'BH', value: 'BH' },
	{ name: 'BI', value: 'BI' },
	{ name: 'BJ', value: 'BJ' },
	{ name: 'BL', value: 'BL' },
	{ name: 'BM', value: 'BM' },
	{ name: 'BN', value: 'BN' },
	{ name: 'BO', value: 'BO' },
	{ name: 'BT', value: 'BT' },
	{ name: 'BW', value: 'BW' },
	{ name: 'BY', value: 'BY' },
	{ name: 'BZ', value: 'BZ' },
	{ name: 'CD', value: 'CD' },
	{ name: 'CF', value: 'CF' },
	{ name: 'CG', value: 'CG' },
	{ name: 'CH', value: 'CH' },
	{ name: 'CI', value: 'CI' },
	{ name: 'CK', value: 'CK' },
	{ name: 'CL', value: 'CL' },
	{ name: 'CM', value: 'CM' },
	{ name: 'CN', value: 'CN' },
	{ name: 'CO', value: 'CO' },
	{ name: 'CR', value: 'CR' },
	{ name: 'CU', value: 'CU' },
	{ name: 'CV', value: 'CV' },
	{ name: 'CW', value: 'CW' },
	{ name: 'CY', value: 'CY' },
	{ name: 'CZ', value: 'CZ' },
	{ name: 'DJ', value: 'DJ' },
	{ name: 'DK', value: 'DK' },
	{ name: 'DM', value: 'DM' },
	{ name: 'DO', value: 'DO' },
	{ name: 'DZ', value: 'DZ' },
	{ name: 'EC', value: 'EC' },
	{ name: 'EE', value: 'EE' },
	{ name: 'EG', value: 'EG' },
	{ name: 'ER', value: 'ER' },
	{ name: 'ET', value: 'ET' },
	{ name: 'FI', value: 'FI' },
	{ name: 'FJ', value: 'FJ' },
	{ name: 'FK', value: 'FK' },
	{ name: 'FO', value: 'FO' },
	{ name: 'GA', value: 'GA' },
	{ name: 'GD', value: 'GD' },
	{ name: 'GE', value: 'GE' },
	{ name: 'GG', value: 'GG' },
	{ name: 'GH', value: 'GH' },
	{ name: 'GI', value: 'GI' },
	{ name: 'GL', value: 'GL' },
	{ name: 'GN', value: 'GN' },
	{ name: 'GP', value: 'GP' },
	{ name: 'GQ', value: 'GQ' },
	{ name: 'GR', value: 'GR' },
	{ name: 'GS', value: 'GS' },
	{ name: 'GT', value: 'GT' },
	{ name: 'GW', value: 'GW' },
	{ name: 'GY', value: 'GY' },
	{ name: 'HK', value: 'HK' },
	{ name: 'HN', value: 'HN' },
	{ name: 'HR', value: 'HR' },
	{ name: 'HT', value: 'HT' },
	{ name: 'HU', value: 'HU' },
	{ name: 'ID', value: 'ID' },
	{ name: 'IE', value: 'IE' },
	{ name: 'IL', value: 'IL' },
	{ name: 'IO', value: 'IO' },
	{ name: 'IQ', value: 'IQ' },
	{ name: 'IR', value: 'IR' },
	{ name: 'IS', value: 'IS' },
	{ name: 'JE', value: 'JE' },
	{ name: 'JM', value: 'JM' },
	{ name: 'JO', value: 'JO' },
	{ name: 'JP', value: 'JP' },
	{ name: 'KE', value: 'KE' },
	{ name: 'KG', value: 'KG' },
	{ name: 'KH', value: 'KH' },
	{ name: 'KM', value: 'KM' },
	{ name: 'KN', value: 'KN' },
	{ name: 'KR', value: 'KR' },
	{ name: 'KW', value: 'KW' },
	{ name: 'KY', value: 'KY' },
	{ name: 'KZ', value: 'KZ' },
	{ name: 'LA', value: 'LA' },
	{ name: 'LB', value: 'LB' },
	{ name: 'LC', value: 'LC' },
	{ name: 'LI', value: 'LI' },
	{ name: 'LK', value: 'LK' },
	{ name: 'LR', value: 'LR' },
	{ name: 'LS', value: 'LS' },
	{ name: 'LT', value: 'LT' },
	{ name: 'LU', value: 'LU' },
	{ name: 'LV', value: 'LV' },
	{ name: 'LY', value: 'LY' },
	{ name: 'MA', value: 'MA' },
	{ name: 'MC', value: 'MC' },
	{ name: 'MD', value: 'MD' },
	{ name: 'ME', value: 'ME' },
	{ name: 'MF', value: 'MF' },
	{ name: 'MG', value: 'MG' },
	{ name: 'MK', value: 'MK' },
	{ name: 'ML', value: 'ML' },
	{ name: 'MM', value: 'MM' },
	{ name: 'MN', value: 'MN' },
	{ name: 'MO', value: 'MO' },
	{ name: 'MP', value: 'MP' },
	{ name: 'MQ', value: 'MQ' },
	{ name: 'MR', value: 'MR' },
	{ name: 'MS', value: 'MS' },
	{ name: 'MT', value: 'MT' },
	{ name: 'MU', value: 'MU' },
	{ name: 'MV', value: 'MV' },
	{ name: 'MW', value: 'MW' },
	{ name: 'MX', value: 'MX' },
	{ name: 'MY', value: 'MY' },
	{ name: 'MZ', value: 'MZ' },
	{ name: 'NA', value: 'NA' },
	{ name: 'NC', value: 'NC' },
	{ name: 'NE', value: 'NE' },
	{ name: 'NF', value: 'NF' },
	{ name: 'NG', value: 'NG' },
	{ name: 'NI', value: 'NI' },
	{ name: 'NL', value: 'NL' },
	{ name: 'NO', value: 'NO' },
	{ name: 'NP', value: 'NP' },
	{ name: 'NR', value: 'NR' },
	{ name: 'NU', value: 'NU' },
	{ name: 'NZ', value: 'NZ' },
	{ name: 'OM', value: 'OM' },
	{ name: 'PA', value: 'PA' },
	{ name: 'PE', value: 'PE' },
	{ name: 'PF', value: 'PF' },
	{ name: 'PG', value: 'PG' },
	{ name: 'PH', value: 'PH' },
	{ name: 'PK', value: 'PK' },
	{ name: 'PL', value: 'PL' },
	{ name: 'PM', value: 'PM' },
	{ name: 'PS', value: 'PS' },
	{ name: 'PT', value: 'PT' },
	{ name: 'PW', value: 'PW' },
	{ name: 'PY', value: 'PY' },
	{ name: 'QA', value: 'QA' },
	{ name: 'RE', value: 'RE' },
	{ name: 'RO', value: 'RO' },
	{ name: 'RS', value: 'RS' },
	{ name: 'RU', value: 'RU' },
	{ name: 'RW', value: 'RW' },
	{ name: 'SA', value: 'SA' },
	{ name: 'SB', value: 'SB' },
	{ name: 'SC', value: 'SC' },
	{ name: 'SD', value: 'SD' },
	{ name: 'SE', value: 'SE' },
	{ name: 'SG', value: 'SG' },
	{ name: 'SI', value: 'SI' },
	{ name: 'SK', value: 'SK' },
	{ name: 'SL', value: 'SL' },
	{ name: 'SM', value: 'SM' },
	{ name: 'SN', value: 'SN' },
	{ name: 'SO', value: 'SO' },
	{ name: 'SR', value: 'SR' },
	{ name: 'SS', value: 'SS' },
	{ name: 'ST', value: 'ST' },
	{ name: 'SV', value: 'SV' },
	{ name: 'SX', value: 'SX' },
	{ name: 'SY', value: 'SY' },
	{ name: 'SZ', value: 'SZ' },
	{ name: 'TC', value: 'TC' },
	{ name: 'TD', value: 'TD' },
	{ name: 'TG', value: 'TG' },
	{ name: 'TH', value: 'TH' },
	{ name: 'TJ', value: 'TJ' },
	{ name: 'TL', value: 'TL' },
	{ name: 'TM', value: 'TM' },
	{ name: 'TN', value: 'TN' },
	{ name: 'TO', value: 'TO' },
	{ name: 'TR', value: 'TR' },
	{ name: 'TT', value: 'TT' },
	{ name: 'TW', value: 'TW' },
	{ name: 'TZ', value: 'TZ' },
	{ name: 'UA', value: 'UA' },
	{ name: 'UG', value: 'UG' },
	{ name: 'UM', value: 'UM' },
	{ name: 'UY', value: 'UY' },
	{ name: 'UZ', value: 'UZ' },
	{ name: 'VC', value: 'VC' },
	{ name: 'VE', value: 'VE' },
	{ name: 'VG', value: 'VG' },
	{ name: 'VN', value: 'VN' },
	{ name: 'VU', value: 'VU' },
	{ name: 'WS', value: 'WS' },
	{ name: 'YE', value: 'YE' },
	{ name: 'YT', value: 'YT' },
	{ name: 'ZA', value: 'ZA' },
	{ name: 'ZM', value: 'ZM' },
	{ name: 'ZW', value: 'ZW' },
];

const targetAudienceOptions = [
    { name: 'Select Target Audience', value: ''},
	{ name: 'Agency / Consultants', value: '1' },
	{ name: 'Creators & Influencers', value: '2' },
	{ name: 'Customer Support & Success', value: '3' },
	{ name: 'Developers & Technical Leads', value: '4' },
	{ name: 'E-Commerce & Retail Managers', value: '5' },
	{ name: 'Enterprise Decision-Makers', value: '6' },
	{ name: 'Finance & Operations Professionals', value: '7' },
	{ name: 'Founders & C-Level Executives', value: '8' },
	{ name: 'Freelancers & Solopreneurs', value: '9' },
	{ name: 'Government & Public Sector Employees', value: '10' },
	{ name: 'HR & Talent Acquisition', value: '11' },
	{ name: 'Healthcare Professionals', value: '12' },
	{ name: 'Hobbyists & Enthusiasts', value: '13' },
	{ name: 'Investors & VCs', value: '14' },
	{ name: 'Job Seekers', value: '15' },
	{ name: 'Legal Professionals', value: '16' },
	{ name: 'Marketing & Sales Professionals', value: '17' },
	{ name: 'Non-Profit Leaders & Staff', value: '18' },
	{ name: 'Parents & Families', value: '19' },
	{ name: 'Product & Project Managers', value: '20' },
	{ name: 'Real Estate Professionals', value: '21' },
	{ name: 'Small-to-Medium Business (SMB) Owners', value: '22' },
	{ name: 'Students & Educators', value: '23' },
];

const targetObjectiveOptions = [
    { name: 'Select Target Objective', value: ''},
	{ name: 'App Installs / Downloads', value: '1' },
	{ name: 'Audience Building (Email/Community)', value: '2' },
	{ name: 'Brand Awareness & Recall', value: '3' },
	{ name: 'Customer Acquisition / Sales', value: '4' },
	{ name: 'Free Trial or Freemium Signups', value: '5' },
	{ name: 'Lead Generation (Top/Mid-Funnel)', value: '6' },
	{ name: 'Loyalty & Referral Program Growth', value: '7' },
	{ name: 'Market & Customer Research', value: '8' },
	{ name: 'New Market Entry', value: '9' },
	{ name: 'Partner & Affiliate Recruitment', value: '10' },
	{ name: 'Product Engagement & Feature Adoption', value: '11' },
	{ name: 'Sales-Ready Leads (Bottom-Funnel)', value: '12' },
	{ name: 'Upsell / Cross-Sell Revenue', value: '13' },
	{ name: 'User Retention & Churn Reduction', value: '14' },
	{ name: 'Waitlist / Pre-Order Signups', value: '15' },
	{ name: 'Website / App Traffic Acquisition', value: '16' },
];

const targetMarketIndustryOptions = [
    { name: 'Select Target Market Industry', value: ''},
	{ name: 'Accommodation', value: '1' },
	{ name: 'Accommodation and Food Services', value: '2' },
	{ name: 'Administrative and Support Services', value: '3' },
	{ name: 'Administrative/Support, Waste Management & Remediation', value: '4' },
	{ name: 'Agriculture, Forestry, Fishing and Hunting', value: '5' },
	{ name: 'Air Transportation', value: '6' },
	{ name: 'Ambulatory Health Care Services', value: '7' },
	{ name: 'Amusement, Gambling, and Recreation Industries', value: '8' },
	{ name: 'Animal Production', value: '9' },
	{ name: 'Apparel Manufacturing', value: '10' },
	{ name: 'Arts, Entertainment, and Recreation', value: '11' },
	{ name: 'Beverage and Tobacco Product Manufacturing', value: '12' },
	{ name: 'Broadcasting (Except Internet)', value: '13' },
	{ name: 'Building Material & Garden Equipment Dealers', value: '14' },
	{ name: 'Chemical Manufacturing', value: '15' },
	{ name: 'Clothing and Clothing Accessories Stores', value: '16' },
	{ name: 'Computer and Electronic Product Manufacturing', value: '17' },
	{ name: 'Construction', value: '18' },
	{ name: 'Construction of Buildings', value: '19' },
	{ name: 'Couriers and Messengers', value: '20' },
	{ name: 'Credit Intermediation and Related Activities', value: '21' },
	{ name: 'Crop Production', value: '22' },
	{ name: 'Data Processing, Hosting, and Related Services', value: '23' },
	{ name: 'Education and Health Services', value: '24' },
	{ name: 'Educational Services', value: '25' },
	{ name: 'Electrical Equipment, Appliance, & Component Mfg', value: '26' },
	{ name: 'Electronics and Appliance Stores', value: '27' },
	{ name: 'Fabricated Metal Product Manufacturing', value: '28' },
	{ name: 'Finance and Insurance', value: '29' },
	{ name: 'Financial Activities', value: '30' },
	{ name: 'Fishing, Hunting and Trapping', value: '31' },
	{ name: 'Food Manufacturing', value: '32' },
	{ name: 'Food Services and Drinking Places', value: '33' },
	{ name: 'Food and Beverage Stores', value: '34' },
	{ name: 'Forestry and Logging', value: '35' },
	{ name: 'Funds, Trusts, and Other Financial Vehicles', value: '36' },
	{ name: 'Furniture and Home Furnishings Stores', value: '37' },
	{ name: 'Furniture and Related Product Manufacturing', value: '38' },
	{ name: 'Gasoline Stations', value: '39' },
	{ name: 'General Merchandise Stores', value: '40' },
	{ name: 'Goods-Producing Industries', value: '41' },
	{ name: 'Health Care and Social Assistance', value: '42' },
	{ name: 'Health and Personal Care Stores', value: '43' },
	{ name: 'Heavy and Civil Engineering Construction', value: '44' },
	{ name: 'Hospitals', value: '45' },
	{ name: 'Information', value: '46' },
	{ name: 'Insurance Carriers and Related Activities', value: '47' },
	{ name: 'Internet Publishing and Broadcasting', value: '48' },
	{ name: 'Leather and Allied Product Manufacturing', value: '49' },
	{ name: 'Leisure and Hospitality', value: '50' },
	{ name: 'Lessors of Nonfinancial Intangible Assets', value: '51' },
	{ name: 'Machinery Manufacturing', value: '52' },
	{ name: 'Management of Companies and Enterprises', value: '53' },
	{ name: 'Manufacturing', value: '54' },
	{ name: 'Merchant Wholesalers, Durable Goods', value: '55' },
	{ name: 'Merchant Wholesalers, Nondurable Goods', value: '56' },
	{ name: 'Mining (Except Oil And Gas)', value: '57' },
	{ name: 'Mining, Quarrying, and Oil and Gas Extraction', value: '58' },
	{ name: 'Miscellaneous Manufacturing', value: '59' },
	{ name: 'Miscellaneous Store Retailers', value: '60' },
	{ name: 'Monetary Authorities - Central Bank', value: '61' },
	{ name: 'Motion Picture and Sound Recording Industries', value: '62' },
	{ name: 'Motor Vehicle and Parts Dealers', value: '63' },
	{ name: 'Museums, Historical Sites, and Similar Institutions', value: '64' },
	{ name: 'Natural Resources and Mining', value: '65' },
	{ name: 'Nonmetallic Mineral Product Manufacturing', value: '66' },
	{ name: 'Nonstore Retailers', value: '67' },
	{ name: 'Nursing and Residential Care Facilities', value: '68' },
	{ name: 'Oil and Gas Extraction', value: '69' },
	{ name: 'Other Information Services', value: '70' },
	{ name: 'Other Services (Except Public Administration)', value: '71' },
	{ name: 'Paper Manufacturing', value: '72' },
	{ name: 'Performing Arts, Spectator Sports, & Related Ind', value: '73' },
	{ name: 'Personal and Laundry Services', value: '74' },
	{ name: 'Petroleum and Coal Products Manufacturing', value: '75' },
	{ name: 'Pipeline Transportation', value: '76' },
	{ name: 'Plastics and Rubber Products Manufacturing', value: '77' },
	{ name: 'Postal Service', value: '78' },
	{ name: 'Primary Metal Manufacturing', value: '79' },
	{ name: 'Printing and Related Support Activities', value: '80' },
	{ name: 'Private Households', value: '81' },
	{ name: 'Professional and Business Services', value: '82' },
	{ name: 'Professional, Scientific, and Technical Services', value: '83' },
	{ name: 'Publishing Industries (Except Internet)', value: '84' },
	{ name: 'Rail Transportation', value: '85' },
	{ name: 'Real Estate', value: '86' },
	{ name: 'Real Estate and Rental and Leasing', value: '87' },
	{ name: 'Religious, Grantmaking, Civic, Professional Orgs', value: '88' },
	{ name: 'Rental and Leasing Services', value: '89' },
	{ name: 'Repair and Maintenance', value: '90' },
	{ name: 'Retail Trade', value: '91' },
	{ name: 'Scenic and Sightseeing Transportation', value: '92' },
	{ name: 'Securities, Commodity Contracts & Investments', value: '93' },
	{ name: 'Service-Providing Industries', value: '94' },
	{ name: 'Social Assistance', value: '95' },
	{ name: 'Specialty Trade Contractors', value: '96' },
	{ name: 'Sporting Goods, Hobby, Book, and Music Stores', value: '97' },
	{ name: 'Support Activities for Agriculture and Forestry', value: '98' },
	{ name: 'Support Activities for Mining', value: '99' },
	{ name: 'Support Activities for Transportation', value: '100' },
	{ name: 'Telecommunications', value: '101' },
	{ name: 'Textile Mills', value: '102' },
	{ name: 'Textile Product Mills', value: '103' },
	{ name: 'Trade, Transportation, and Utilities', value: '104' },
	{ name: 'Transit and Ground Passenger Transportation', value: '105' },
	{ name: 'Transportation Equipment Manufacturing', value: '106' },
	{ name: 'Transportation and Warehousing', value: '107' },
	{ name: 'Truck Transportation', value: '108' },
	{ name: 'Utilities', value: '109' },
	{ name: 'Warehousing and Storage', value: '110' },
	{ name: 'Waste Management and Remediation Services', value: '111' },
	{ name: 'Water Transportation', value: '112' },
	{ name: 'Wholesale Electronic Markets and Agents/Brokers', value: '113' },
	{ name: 'Wholesale Trade', value: '114' },
	{ name: 'Wood Product Manufacturing', value: '115' },
];

export class ApexVerify implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'ApexVerify',
		name: 'apexVerify',
		icon: 'file:../../icons/apexverify.svg',
		group: ['transform'],
		version: 1,
        subtitle: '={{$parameter["operation"]}}',
		description: 'Verify emails, phone numbers, and addresses with real-time accuracy. Keep your contact data clean, compliant, and reliable with our all-in-one suite.',
		defaults: {
			name: 'ApexVerify',
		},
		inputs: [NodeConnectionTypes.Main],
        outputs: [NodeConnectionTypes.Main],
        usableAsTool: true,
		credentials: [
			{
				name: 'apexVerifyApi',
				required: true,
			},
		],
		requestDefaults: {
			baseURL: 'https://api.apexverify.com',
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
			},
		},
		properties: [
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Verify Email or Phone',
						value: 'verify',
						description: 'Validate an email address or phone number',
						action: 'Verify email or phone',
					},
				],
				default: 'verify',
			},

			{
				displayName: 'Data Type',
				name: 'type',
				type: 'options',
				required: true,
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				options: [
					{
						name: 'Email Address',
						value: 'email',
					},
					{
						name: 'Phone Number',
						value: 'phone',
					},
				],
				default: 'email',
				description: 'Select whether you are verifying an email address or a phone number',
			},
			{
				displayName: 'Email or Phone to Verify',
				name: 'unit',
				type: 'string',
				required: true,
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				default: '',
				placeholder: 'hello@apexverify.com',
				description: 'Enter the email address or phone number to verify',
			},
			{
				displayName: 'Target Country',
				name: 'target_country',
				type: 'options',
				required: true,
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				options: targetCountryOptions,
				default: 'US',
				description: 'Country against which the email or phone should be processed',
			},

			{
				displayName: 'Target Audience',
				name: 'target_audience',
				type: 'options',
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				options: targetAudienceOptions,
				default: '',
				description: 'Optional. Select the target audience for the verification context.',
			},
			{
				displayName: 'Target Market Industry',
				name: 'target_market_industry',
				type: 'options',
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				options: targetMarketIndustryOptions,
				default: '',
				description: 'Optional. Select the target market industry for the verification context.',
			},
			{
				displayName: 'Target Objective',
				name: 'target_objective',
				type: 'options',
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				options: targetObjectiveOptions,
				default: '',
				description: 'Optional. Select the target objective for the verification context.',
			},

			{
				displayName: 'Use Account Cache',
				name: 'use_account_cache',
				type: 'boolean',
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				default: true,
				description: 'Whether to use previous verification results from your ApexVerify account cache when available',
			},
			{
				displayName: 'Max Account Cache Backoff',
				name: 'max_account_cache_backoff',
				type: 'number',
				typeOptions: {
					minValue: 1,
					maxValue: 180,
				},
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				default: 30,
				description: 'Maximum number of days to look back in account cache. Min: 1. Max: 180.',
			},
			{
				displayName: 'Use Global Cache',
				name: 'use_global_cache',
				type: 'boolean',
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				default: true,
				description: 'Whether to use anonymized global cache results when available',
			},
			{
				displayName: 'Max Global Cache Backoff',
				name: 'max_global_cache_backoff',
				type: 'number',
				typeOptions: {
					minValue: 1,
					maxValue: 180,
				},
				displayOptions: {
					show: {
						operation: ['verify'],
					},
				},
				default: 30,
				description: 'Maximum number of days to look back in global cache. Min: 1. Max: 180.',
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];

		for (let i = 0; i < items.length; i++) {
			try {
				const operation = this.getNodeParameter('operation', i) as string;

				if (operation !== 'verify') {
					throw new NodeOperationError(
						this.getNode(),
						`Unsupported operation: ${operation}`,
						{ itemIndex: i },
					);
				}

				const body: Record<string, unknown> = {
					type: this.getNodeParameter('type', i),
					target_country: this.getNodeParameter('target_country', i),
					unit: this.getNodeParameter('unit', i),
					target_audience: this.getNodeParameter('target_audience', i, ''),
					target_market_industry: this.getNodeParameter('target_market_industry', i, ''),
					target_objective: this.getNodeParameter('target_objective', i, ''),
					use_account_cache: this.getNodeParameter('use_account_cache', i, true),
					max_account_cache_backoff: this.getNodeParameter('max_account_cache_backoff', i, 30),
					use_global_cache: this.getNodeParameter('use_global_cache', i, true),
					max_global_cache_backoff: this.getNodeParameter('max_global_cache_backoff', i, 30),
				};

				for (const key of Object.keys(body)) {
					if (body[key] === '' || body[key] === null || body[key] === undefined) {
						delete body[key];
					}
				}

				const responseData = await this.helpers.httpRequestWithAuthentication.call(
					this,
					'apexVerifyApi',
					{
						method: 'POST',
						url: 'https://api.apexverify.com/v1/unit',
						body,
						json: true,
					},
				);

				returnData.push({
					json: responseData,
					pairedItem: {
						item: i,
					},
				});
			} catch (error) {
				const err = error as {
					response?: {
						statusCode?: number;
						body?: {
							message?: string;
							detail?: unknown;
						};
					};
					message?: string;
				};

				if (err.response?.body?.message) {
					throw new NodeApiError(this.getNode(), err.response.body as JsonObject, {
						message: err.response.body.message,
						itemIndex: i,
					});
				}

				if (this.continueOnFail()) {
					returnData.push({
						json: {
							error: err.message || 'ApexVerify request failed',
						},
						pairedItem: {
							item: i,
						},
					});
					continue;
				}

				throw new NodeApiError(this.getNode(), error as JsonObject, {
                    itemIndex: i,
                });
			}
		}

		return [returnData];
	}
}